export const GET_TEXT = 'GET_TEXT'
export const GET_CURRENCY = 'GET_CURRENCY'
export const GET_INPUT = 'GET_INPUT'
export const GET_NOTE = 'GET_NOTE'
export const GET_ERRORS = 'GET_ERRORS'
export const GET_COMPARE_MIN = 'GET_COMPARE_MIN'
export const GET_COMPARE_MAX = 'GET_COMPARE_MAX'
